

services:
  db:
    container_name: database
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mafia
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

#  redis:
#    container_name: redis
#
#    image: redis
#    ports:
#      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: ./compose/springboot/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - db
#      - redis
    restart: on-failure
volumes:
  db-data:
